[#2]: update last script called by dd-publish to conventions

diff --git a/code/bin/dd-push-finished-release b/code/bin/dd-push-finished-release
--- a/code/bin/dd-push-finished-release
+++ b/code/bin/dd-push-finished-release
@@ -9,85 +9,154 @@
 # created : 2016-06-06
 
 
+# NOTE: see also ./dd-release
+
+
 echo
-echo 'dd-push-finished-release:'
+echo 'push finished release'
 echo
-
-# -----------------------------------------------------------------------------
-# determine platform: http://stackoverflow.com/a/18434831
-
-# NOTE: on OS X, install GNU sed and grep using
-# brew tap homebrew/dupes; brew install gnu-sed grep
-# http://apple.stackexchange.com/a/69332
-
-case "${OSTYPE}" in
-    darwin*)
-        grep='ggrep'
-        sed='gsed'
-        ;;
-    linux*)
-        grep='grep'
-        sed='sed'
-        ;;
-    *)
-        echo "Unsupported operating system: ${OSTYPE}"
-        exit -1
-        ;;
-esac
-
-
-# -----------------------------------------------------------------------------
-# process command line arguments
-
-if [ $# -ne 1 ]
-then
-    echo "Usage: $(basename "$0") <repository root folder>"
-    exit -1
-else
-    if [ ! -e "$1" ]
-    then
-        echo "$1: No such file or directory"
-        exit -1
-    fi
-    if [ ! -d "$1" ]
-    then
-        echo "$1: Not a directory"
-        exit -1
-    fi
-fi
-
-# TODO: prevent processing repo this file is in during development ?
-# TODO: verify required executables are available before using them ?
-# TODO: script return value when run as Jenkins job ?!?
-# TODO: add leading zero to calender week in release name
 
 
 # -----------------------------------------------------------------------------
 # configure script parameters
 
-# absolute path to the root folder of the repository to process
-repo_root="$(realpath "$1")"
+# absolute path to this script: http://stackoverflow.com/a/9107028
+here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 
-# release branch prefix; 'release' as per git flow convention
-# TODO: remove this with the inactive branch deletion below
-# branch_release_prefix='release'
+# path from this script to project root
+path_to_proj_root='../..'
 
-# develop branch; 'develop' as per git flow convention
-branch_develop='develop'
+# absolute path to BashLib library file
+path_to_bashlib='/usr/local/lib/dd-bash-lib.sh'
 
-# master branch; 'master' as per git flow convention
-branch_master='master'
+# path to ReleaseTools library file, relative to project root
+path_to_rt_lib='code/bin/dd-rt-library.sh'
 
-# regex pattern for most recent commit message
-message_regex="^Merge tag '(.*)' into develop"
+# array with alphabetical list of tools called by this script
+# shellcheck disable=SC2034
+req_tools=('git' 'jq' 'realpath' 'yq')
+
+# array with paths to append to PATH
+# shellcheck disable=SC2034
+ext_paths=()
 
 
-# NOTE: pushd / popd require bash
-pushd "${repo_root}" > /dev/null
+# -----------------------------------------------------------------------------
+# load BashLib library
+
+# shellcheck disable=SC1090
+if output="$(source "${path_to_bashlib}" 2>&1)"
+then
+    source "${path_to_bashlib}"
+else
+    echo "${output}"
+    exit 1
+fi
+
+
+# -----------------------------------------------------------------------------
+# run BashLib boilerplate functions
+
+if ! configure_platform              ; then exit 1; fi
+if ! extend_path req_tools ext_paths ; then exit 1; fi
+
+
+# -----------------------------------------------------------------------------
+# configure script parameters, cont.
+
+# absolute, canonical path to project root
+path_to_proj_root="$(realpath "${here}/${path_to_proj_root}")"
+
+# absolute, canonical path to ReleaseTools library file
+path_to_rt_lib="${path_to_proj_root}/${path_to_rt_lib}"
+
+
+# -----------------------------------------------------------------------------
+# load ReleaseTools library
+
+# shellcheck disable=SC1090
+if output="$(source "${path_to_rt_lib}" 2>&1)"
+then
+    source "${path_to_rt_lib}"
+else
+    echo "${output}"
+    exit 1
+fi
+
+
+# -----------------------------------------------------------------------------
+# run ReleaseTools boilerplate functions
+
+if ! get_script_args "${@}"; then exit 1; fi
+
+
+# -----------------------------------------------------------------------------
+# configure script parameters, cont. 2
+
+# absolute, canonical path to the target project / repository root folder
+repo_root="$(realpath "${repo_root}")"
+
+# absolute path to target project configuration file
+# shellcheck disable=SC2154
+conf_file="${repo_root}/${path_to_target_conf}"
+
+# arguments passed to git (not to a sub-command) with every call
+git_args=('-C' "${repo_root}")
+
+
+# -----------------------------------------------------------------------------
+# load script configuration
+
+echo
+
+echo -n 'Load script configuration file: '
+# shellcheck disable=SC2154
+if output="$(yq read "${conf_file}" --tojson 2>&1)"
+then
+    echo 'OK'
+    config="${output}"
+else
+    echo 'ERROR'
+    echo "${output}"
+    exit 1
+fi
+
+echo -n 'Extract script configuration attributes: '
+# TODO: remove once more attributes
+# shellcheck disable=SC2043
+for attr in version
+do
+    output="$(jq -r ".${attr}" <<< "${config}")"
+    # https://unix.stackexchange.com/a/68349
+    # https://unix.stackexchange.com/a/41418
+    if [ -n "${output}" ] && [ "${output}" != 'null' ]
+    then
+        declare "${attr}"="${output}"
+    else
+        echo 'ERROR'
+        echo "Failed to get ${attr} attribute from configuration"
+        exit 1
+    fi
+done
+echo 'OK'
+
+
+# -----------------------------------------------------------------------------
+# configure script parameters, cont. 3
+
+# shellcheck disable=SC2154
+major="$(jq -r '.major' <<< "${version}")"
+minor="$(jq -r '.minor' <<< "${version}")"
+patch="$(jq -r '.patch' <<< "${version}")"
+
+release_name="${major}.${minor}.${patch}"
 
 
 # -----------------------------------------------------------------------------
 # push the finished release
+
+
+# TODO: create script to verify these prerequisites and run earlier than here
 
 # NOTE: this script expects to be called in the following context:
 # dd-publish has finished the release, i.e. merged the release branch to master
@@ -95,55 +164,20 @@ pushd "${repo_root}" > /dev/null
 # the tag and the changes merged to develop and master must be pushed to origin,
 # the release branch must be deleted at origin
 
-# TODO: make origin configurable ? detect default remote ?
-# TODO: test if tag exists locally and only push if it does ?
-# TODO: deal with improperly set up remotes not using 'origin':
-# git flow heavily relies on that convention:
-#   fatal: No configured push destination.
-#   Either specify the URL from the command-line or configure a remote repository using
-#       git remote add <name> <url>
-#   and then push using the remote name
-#       git push <name>
 
-# name of the release in progress: at this point, the release branch has already
-# been deleted and the best way to determine the name of the release whose
-# changes to push seems to be to look at the most recent git commit message
-
-# http://stackoverflow.com/a/7293026
-# git log -1 --pretty=%B sample output:
-# Merge tag '2016.23.02' into develop
-#
-# automatically_created_release_tag 2016.23.02
-#
-
-release_name="$(git log -1 --pretty=%B            \
-                    | "${grep}" -E "${message_regex}" \
-                    | "${sed}" -r -e "s|${message_regex}|\1|g")"
-
-if [ -z "${release_name}" ]
-then
-    echo "Failed to determine name of current release"
-    exit -1
-fi
-
-# TODO: see dd-upload-artifacts
-if [ "$(hostname)" = 'vm-build-nice' ]
-then
-    # shellcheck disable=SC2034
-    SSH_AUTH_SOCK='/home/bob.the.builder/.ssh/ssh_auth_sock'
-fi
+echo
 
 # NOTE: tag name is equal to release name by git flow convention
-echo "Push release tag ${release_name} to origin:"
-git push origin "${release_name}"
-
-res="$?"
-
-if [ "${res}" -ne 0 ]
+# shellcheck disable=SC2154
+echo -n "Push release tag ${release_name} to ${remote_default_name}: "
+if output="$(git "${git_args[@]}" push "${remote_default_name}" \
+                                       "${release_name}" 2>&1)"
 then
-    # git push prints its own error messages
-    popd > /dev/null
-    exit "${res}"
+    echo 'OK'
+else
+    echo 'ERROR'
+    echo "${output}"
+    exit 1
 fi
 
 # TODO: git pull to deal with push rejections due to upstream changes:
@@ -155,50 +189,31 @@ fi
 #   hint: 'git pull ...') before pushing again.
 #   hint: See the 'Note about fast-forwards' in 'git push --help' for details.
 
-echo "Push changes merged to ${branch_develop} to origin:"
-git push origin "${branch_develop}"
-
-res="$?"
-
-if [ "${res}" -ne 0 ]
+# shellcheck disable=SC2154
+echo -n "Push changes merged to ${branch_develop} to ${remote_default_name}: "
+if output="$(git "${git_args[@]}" push "${remote_default_name}" \
+                                       "${branch_develop}" 2>&1)"
 then
-    # git push prints its own error messages
-    popd > /dev/null
-    exit "${res}"
+    echo 'OK'
+else
+    echo 'ERROR'
+    echo "${output}"
+    exit 1
 fi
 
-echo "Push changes merged to ${branch_master} to origin:"
-git push origin "${branch_master}"
-
-res="$?"
-
-if [ "${res}" -ne 0 ]
+# shellcheck disable=SC2154
+echo -n "Push changes merged to ${branch_master} to ${remote_default_name}: "
+if output="$(git "${git_args[@]}" push "${remote_default_name}" \
+                                       "${branch_master}" 2>&1)"
 then
-    # git push prints its own error messages
-    popd > /dev/null
-    exit "${res}"
+    echo 'OK'
+else
+    echo 'ERROR'
+    echo "${output}"
+    exit 1
 fi
-
-# TODO: as of git flow 1.8.0-1 Debian package on Debian 8.4 64-bit,
-# this seems no longer required, the remote release branch is already
-# deleted by git flow release finish --> delete only if exists (?)
-#
-# echo "Delete release branch ${branch_release_prefix}/${release_name} on origin:"
-# git push origin --delete "${branch_release_prefix}/${release_name}"
-#
-# res="$?"
-#
-# if [ "${res}" -ne 0 ]
-# then
-#     # git push prints its own error messages
-#     popd > /dev/null
-#     exit "${res}"
-# fi
-
-
-popd > /dev/null
 
 
 echo
-echo 'dd-push-finished-release: success'
+echo 'pushing finished release complete'
 echo
