[#2]: align script names with convention: dd-* --> dd-rt-*

diff --git a/code/bin/dd-rt-create-release-notes b/code/bin/dd-rt-create-release-notes
--- a/code/bin/dd-rt-create-release-notes
+++ b/code/bin/dd-rt-create-release-notes
@@ -1,22 +1,22 @@
 #!/usr/bin/env bash
 
-# dd-update-project-version
+# dd-rt-create-release-notes
 #
-# update semantic version in project configuration
+# create release notes
 #
 # author  : stefan schablowski
 # contact : stefan.schablowski@desmodyne.com
 # created : 2016-06-03
 
 
-# NOTE: see also ./dd-release
+# NOTE: see also ./dd-rt-release
 
-# major.minor.patch: http://semver.org
-# https://en.wikipedia.org/wiki/Software_versioning
+
+# TODO: this should be done later, so hotfixes are also mentioned
 
 
 echo
-echo 'update project version'
+echo 'create release notes'
 echo
 
 
@@ -80,6 +80,7 @@ path_to_rt_lib="${path_to_proj_root}/${path_to_rt_lib}"
 # shellcheck disable=SC1090
 if output="$(source "${path_to_rt_lib}" 2>&1)"
 then
+    # shellcheck disable=SC1090
     source "${path_to_rt_lib}"
 else
     echo "${output}"
@@ -90,7 +91,7 @@ fi
 # -----------------------------------------------------------------------------
 # run ReleaseTools boilerplate functions
 
-if ! get_script_args_opt_arg "${@}"; then exit 1; fi
+if ! get_script_args "${@}"; then exit 1; fi
 
 
 # -----------------------------------------------------------------------------
@@ -102,6 +103,10 @@ repo_root="$(realpath "${repo_root}")"
 # absolute path to target project configuration file
 # shellcheck disable=SC2154
 conf_file="${repo_root}/${path_to_target_conf}"
+
+# absolute path to release notes folder
+# shellcheck disable=SC2154
+path_to_release_notes="${repo_root}/${path_to_release_notes}"
 
 # arguments passed to git (not to a sub-command) with every call
 git_args=('-C' "${repo_root}")
@@ -146,101 +151,88 @@ echo 'OK'
 # configure script parameters, cont. 3
 
 # shellcheck disable=SC2154
-old_major="$(jq -r '.major' <<< "${version}")"
-old_minor="$(jq -r '.minor' <<< "${version}")"
-old_patch="$(jq -r '.patch' <<< "${version}")"
+major="$(jq -r '.major' <<< "${version}")"
+minor="$(jq -r '.minor' <<< "${version}")"
+patch="$(jq -r '.patch' <<< "${version}")"
 
-# if no explicit version is passed as cmd line arg,
-# increment the one defined in project > version conf
-# shellcheck disable=SC2154
-if [ -z "${semver}" ]
-then
-    new_major="${old_major}"
-    new_minor="${old_minor}"
-    new_patch=$((old_patch + 1))
-
-# otherwise validate the cmd line arg and use it if valid
-else
-    current_semver="${old_major}.${old_minor}.${old_patch}"
-
-    # TODO: handle leading zeroes in cmd line arg ?
-    if [[ ! "${semver}" > "${current_semver}" ]]
-    then
-        # shellcheck disable=SC2059
-        msg="$(printf "${err_msg_git_conf}" \
-                      "${semver}" "${current_semver}" "${conf_file}")"
-        echo "${msg}"
-        exit 1
-    fi
-
-    new_major="$("${gsed}" -e "${sedex_semver_major}" <<< "${semver}")"
-    new_minor="$("${gsed}" -e "${sedex_semver_minor}" <<< "${semver}")"
-    new_patch="$("${gsed}" -e "${sedex_semver_patch}" <<< "${semver}")"
-fi
-
-release_name="${new_major}.${new_minor}.${new_patch}"
+release_name="${major}.${minor}.${patch}"
 
 
 # -----------------------------------------------------------------------------
-# update project version
-
-# NOTE: extra work to maintain formatting and comments in configuration file
-# NOTE: this opens conf_file a second time, this time accessing text natively
+# create release notes
 
 echo
+echo "Create notes for release ${release_name} in ${repo_root}:"
+
+# create output folder if required
+if [ ! -d "${path_to_release_notes}" ]
+then
+    mkdir -p "${path_to_release_notes}"
+fi
+
+# get commit SHA1 hashes of previous and this release branch
+# TODO: make master and HEAD configurable ?
+prev_release="$(git "${git_args[@]}" rev-parse --verify master)"
+this_release="$(git "${git_args[@]}" rev-parse --verify HEAD)"
+
+# TODO: use dd-date for this
+# shellcheck disable=SC2154
+timestamp="$(date "${release_notes_date_format}")"
+
+# render release notes filename
+# shellcheck disable=SC2059,SC2154
+release_notes_file="$(printf "${release_notes_tmpl}" \
+                             "${timestamp}" "${release_name}")"
+
+path_to_release_notes_file="${path_to_release_notes}/${release_notes_file}"
+
+
+# TODO: --format=format:<string> ?
+# TODO: internal / external release notes ?
+# TODO: make order and format configurable ?
+
+# http://stackoverflow.com/a/2099492
+echo -n 'Get details of commits to go into release: '
+# shellcheck disable=SC2154
+if output="$(git "${git_args[@]}" rev-list --topo-order --format=fuller \
+               "${prev_release}..${this_release}")"
+then
+    echo 'OK'
+    release_notes="${output}"
+else
+    echo 'ERROR'
+    echo "${output}"
+    exit 1
+fi
+
+echo -n 'Save commit details to release notes file: '
+if output="$(echo "${release_notes}" | awk '$0="    "$0' \
+              > "${path_to_release_notes_file}" 2>&1)"
+then
+    echo 'OK'
+else
+    echo 'ERROR'
+    echo "${output}"
+    exit 1
+fi
+
+echo -n 'Stage changes to release notes file: '
+if output="$(git "${git_args[@]}" add "${path_to_release_notes_file}" 2>&1)"
+then
+    echo 'OK'
+else
+    echo 'ERROR'
+    echo "${output}"
+    exit 1
+fi
 
 # shellcheck disable=SC2059,SC2154
-sedex_yaml_version="$(printf "${sedex_yaml_version_tmpl}"                   \
-                             "${old_major}" "${old_minor}" "${old_patch}"   \
-                             "${new_major}" "${new_minor}" "${new_patch}")"
-
-echo -n 'Create new version section: '
-# https://unix.stackexchange.com/a/152389
-# TODO: this leaks errors displayed by earlier commands
-# TODO: can this be done with <<< ?
-# shellcheck disable=SC2002,SC2154
-if output="$(cat "${conf_file}"                     \
-              | tr '\n' '\r'                        \
-              | "${sed}" -e "${sedex_yaml_version}" \
-              | tr '\r' '\n')"
-then
-    echo 'OK'
-    config="${output}"
-else
-    echo 'ERROR'
-    echo "${output}"
-    exit 1
-fi
-
-echo -n 'Save version section to conf file: '
-# TODO: does this pipe errors into the file ?
-# shellcheck disable=SC2116
-if output="$(echo "${config}" > "${conf_file}" 2>&1)"
-then
-    echo 'OK'
-else
-    echo 'ERROR'
-    echo "${output}"
-    exit 1
-fi
-
-echo -n 'Stage changes to conf file: '
-if output="$(git "${git_args[@]}" add "${conf_file}" 2>&1)"
-then
-    echo 'OK'
-else
-    echo 'ERROR'
-    echo "${output}"
-    exit 1
-fi
-
-# shellcheck disable=SC2059,SC2154
-commit_msg="$(printf "${commit_msg_version_tmpl}" "${release_name}")"
+commit_msg="$(printf "${commit_msg_release_tmpl}" "${release_name}")"
 
 echo -n 'Commit changes to conf file: '
 # shellcheck disable=SC2154
 if output="$(git "${git_args[@]}" commit \
-               -m "${commit_msg}" "${conf_file}" 2>&1)"
+               -m "${commit_msg}" "${path_to_release_notes_file}" 2>&1)"
 then
     echo 'OK'
 else
@@ -251,5 +243,5 @@ fi
 
 
 echo
-echo 'project version update complete'
+echo 'release notes creation complete'
 echo
diff --git a/code/bin/dd-rt-push-finished-release b/code/bin/dd-rt-push-finished-release
--- a/code/bin/dd-rt-push-finished-release
+++ b/code/bin/dd-rt-push-finished-release
@@ -1,19 +1,19 @@
 #!/usr/bin/env bash
 
-# dd-verify-user-configuration
+# dd-rt-push-finished-release
 #
-# verify git configuration for current user
+# push a finished release to remote git repo
 #
 # author  : stefan schablowski
 # contact : stefan.schablowski@desmodyne.com
-# created : 2016-06-16
+# created : 2016-06-06
 
 
-# NOTE: see also ./dd-release
+# NOTE: see also ./dd-rt-release
 
 
 echo
-echo 'verify git user configuration'
+echo 'push finished release'
 echo
 
 
@@ -100,6 +100,9 @@ repo_root="$(realpath "${repo_root}")"
 # shellcheck disable=SC2154
 conf_file="${repo_root}/${path_to_target_conf}"
 
+# arguments passed to git (not to a sub-command) with every call
+git_args=('-C' "${repo_root}")
+
 
 # -----------------------------------------------------------------------------
 # load script configuration
@@ -121,9 +124,11 @@ fi
 echo -n 'Extract script configuration attributes: '
 # TODO: remove once more attributes
 # shellcheck disable=SC2043
-for attr in users
+for attr in version
 do
     output="$(jq -r ".${attr}" <<< "${config}")"
+    # https://unix.stackexchange.com/a/68349
+    # https://unix.stackexchange.com/a/41418
     if [ -n "${output}" ] && [ "${output}" != 'null' ]
     then
         declare "${attr}"="${output}"
@@ -137,61 +142,78 @@ echo 'OK'
 
 
 # -----------------------------------------------------------------------------
-# verify user configuration
+# configure script parameters, cont. 3
+
+# shellcheck disable=SC2154
+major="$(jq -r '.major' <<< "${version}")"
+minor="$(jq -r '.minor' <<< "${version}")"
+patch="$(jq -r '.patch' <<< "${version}")"
+
+release_name="${major}.${minor}.${patch}"
+
+
+# -----------------------------------------------------------------------------
+# push the finished release
+
+
+# TODO: create script to verify these prerequisites and run earlier than here
+
+# NOTE: this script expects to be called in the following context:
+# dd-rt-publish has finished the release, i.e. merged the release branch to master
+# and to develop, deleted the local release branch and created a release tag;
+# the tag and the changes merged to develop and master must be pushed to origin,
+# the release branch must be deleted at origin
+
 
 echo
-echo -n 'Verify user git configuration: '
 
-git_username="$( git -C "${repo_root}" config user.name)"
-git_useremail="$(git -C "${repo_root}" config user.email)"
-
-if [ -n "${git_username}" ] && [ -n "${git_useremail}" ]
+# NOTE: tag name is equal to release name by git flow convention
+# shellcheck disable=SC2154
+echo -n "Push release tag ${release_name} to ${remote_default_name}: "
+if output="$(git "${git_args[@]}" push "${remote_default_name}" \
+                                       "${release_name}" 2>&1)"
 then
     echo 'OK'
 else
-    echo 'incomplete'
+    echo 'ERROR'
+    echo "${output}"
+    exit 1
+fi
 
-    current_username="$(id -u -n)"
+# TODO: git pull to deal with push rejections due to upstream changes:
+# To <git repo url>
+#    ! [rejected]        develop -> develop (non-fast-forward)
+#   error: failed to push some refs to '<git repo url>'
+#   hint: Updates were rejected because the tip of your current branch is behind
+#   hint: its remote counterpart. Integrate the remote changes (e.g.
+#   hint: 'git pull ...') before pushing again.
+#   hint: See the 'Note about fast-forwards' in 'git push --help' for details.
 
-    # set details for known users automatically
-    # shellcheck disable=SC2154
-    mapfile -t known_users <<< "$(jq -r 'keys[]' <<< "${users}")"
+# shellcheck disable=SC2154
+echo -n "Push changes merged to ${branch_develop} to ${remote_default_name}: "
+if output="$(git "${git_args[@]}" push "${remote_default_name}" \
+                                       "${branch_develop}" 2>&1)"
+then
+    echo 'OK'
+else
+    echo 'ERROR'
+    echo "${output}"
+    exit 1
+fi
 
-    if ! grep -q "${current_username}" <<< "${known_users[*]}"
-    then
-        # shellcheck disable=SC2154
-        echo "${err_msg_git_conf}"
-        echo
-        exit 1
-    else
-        username="$(jq -r ".[\"${current_username}\"].name"  <<< "${users}")"
-        email="$(   jq -r ".[\"${current_username}\"].email" <<< "${users}")"
-
-        echo "configure settings for known user ${current_username}:"
-
-        echo -n "  git config user.name '${username}': "
-        if output="$(git -C "${repo_root}" config user.name "'${username}'")"
-        then
-            echo 'OK'
-        else
-            echo 'ERROR'
-            echo "    ${output}"
-            exit 1
-        fi
-
-        echo -n "  git config user.email '${email}': "
-        if output="$(git -C "${repo_root}" config user.email "'${email}'")"
-        then
-            echo 'OK'
-        else
-            echo 'ERROR'
-            echo "    ${output}"
-            exit 1
-        fi
-    fi
+# shellcheck disable=SC2154
+echo -n "Push changes merged to ${branch_master} to ${remote_default_name}: "
+if output="$(git "${git_args[@]}" push "${remote_default_name}" \
+                                       "${branch_master}" 2>&1)"
+then
+    echo 'OK'
+else
+    echo 'ERROR'
+    echo "${output}"
+    exit 1
 fi
 
 
 echo
-echo 'git user configuration verification complete'
+echo 'pushing finished release complete'
 echo
diff --git a/code/bin/dd-rt-update-project-version b/code/bin/dd-rt-update-project-version
--- a/code/bin/dd-rt-update-project-version
+++ b/code/bin/dd-rt-update-project-version
@@ -1,19 +1,22 @@
 #!/usr/bin/env bash
 
-# dd-push-finished-release
+# dd-rt-update-project-version
 #
-# push a finished release to remote git repo
+# update semantic version in project configuration
 #
 # author  : stefan schablowski
 # contact : stefan.schablowski@desmodyne.com
-# created : 2016-06-06
+# created : 2016-06-03
 
 
-# NOTE: see also ./dd-release
+# NOTE: see also ./dd-rt-release
+
+# major.minor.patch: http://semver.org
+# https://en.wikipedia.org/wiki/Software_versioning
 
 
 echo
-echo 'push finished release'
+echo 'update project version'
 echo
 
 
@@ -87,7 +90,7 @@ fi
 # -----------------------------------------------------------------------------
 # run ReleaseTools boilerplate functions
 
-if ! get_script_args "${@}"; then exit 1; fi
+if ! get_script_args_opt_arg "${@}"; then exit 1; fi
 
 
 # -----------------------------------------------------------------------------
@@ -127,8 +130,6 @@ echo -n 'Extract script configuration attributes: '
 for attr in version
 do
     output="$(jq -r ".${attr}" <<< "${config}")"
-    # https://unix.stackexchange.com/a/68349
-    # https://unix.stackexchange.com/a/41418
     if [ -n "${output}" ] && [ "${output}" != 'null' ]
     then
         declare "${attr}"="${output}"
@@ -145,33 +146,76 @@ echo 'OK'
 # configure script parameters, cont. 3
 
 # shellcheck disable=SC2154
-major="$(jq -r '.major' <<< "${version}")"
-minor="$(jq -r '.minor' <<< "${version}")"
-patch="$(jq -r '.patch' <<< "${version}")"
+old_major="$(jq -r '.major' <<< "${version}")"
+old_minor="$(jq -r '.minor' <<< "${version}")"
+old_patch="$(jq -r '.patch' <<< "${version}")"
 
-release_name="${major}.${minor}.${patch}"
+# if no explicit version is passed as cmd line arg,
+# increment the one defined in project > version conf
+# shellcheck disable=SC2154
+if [ -z "${semver}" ]
+then
+    new_major="${old_major}"
+    new_minor="${old_minor}"
+    new_patch=$((old_patch + 1))
+
+# otherwise validate the cmd line arg and use it if valid
+else
+    current_semver="${old_major}.${old_minor}.${old_patch}"
+
+    # TODO: handle leading zeroes in cmd line arg ?
+    if [[ ! "${semver}" > "${current_semver}" ]]
+    then
+        # shellcheck disable=SC2059
+        msg="$(printf "${err_msg_git_conf}" \
+                      "${semver}" "${current_semver}" "${conf_file}")"
+        echo "${msg}"
+        exit 1
+    fi
+
+    new_major="$("${gsed}" -e "${sedex_semver_major}" <<< "${semver}")"
+    new_minor="$("${gsed}" -e "${sedex_semver_minor}" <<< "${semver}")"
+    new_patch="$("${gsed}" -e "${sedex_semver_patch}" <<< "${semver}")"
+fi
+
+release_name="${new_major}.${new_minor}.${new_patch}"
 
 
 # -----------------------------------------------------------------------------
-# push the finished release
+# update project version
 
-
-# TODO: create script to verify these prerequisites and run earlier than here
-
-# NOTE: this script expects to be called in the following context:
-# dd-publish has finished the release, i.e. merged the release branch to master
-# and to develop, deleted the local release branch and created a release tag;
-# the tag and the changes merged to develop and master must be pushed to origin,
-# the release branch must be deleted at origin
-
+# NOTE: extra work to maintain formatting and comments in configuration file
+# NOTE: this opens conf_file a second time, this time accessing text natively
 
 echo
 
-# NOTE: tag name is equal to release name by git flow convention
-# shellcheck disable=SC2154
-echo -n "Push release tag ${release_name} to ${remote_default_name}: "
-if output="$(git "${git_args[@]}" push "${remote_default_name}" \
-                                       "${release_name}" 2>&1)"
+# shellcheck disable=SC2059,SC2154
+sedex_yaml_version="$(printf "${sedex_yaml_version_tmpl}"                   \
+                             "${old_major}" "${old_minor}" "${old_patch}"   \
+                             "${new_major}" "${new_minor}" "${new_patch}")"
+
+echo -n 'Create new version section: '
+# https://unix.stackexchange.com/a/152389
+# TODO: this leaks errors displayed by earlier commands
+# TODO: can this be done with <<< ?
+# shellcheck disable=SC2002,SC2154
+if output="$(cat "${conf_file}"                     \
+              | tr '\n' '\r'                        \
+              | "${sed}" -e "${sedex_yaml_version}" \
+              | tr '\r' '\n')"
+then
+    echo 'OK'
+    config="${output}"
+else
+    echo 'ERROR'
+    echo "${output}"
+    exit 1
+fi
+
+echo -n 'Save version section to conf file: '
+# TODO: does this pipe errors into the file ?
+# shellcheck disable=SC2116
+if output="$(echo "${config}" > "${conf_file}" 2>&1)"
 then
     echo 'OK'
 else
@@ -180,19 +224,8 @@ else
     exit 1
 fi
 
-# TODO: git pull to deal with push rejections due to upstream changes:
-# To <git repo url>
-#    ! [rejected]        develop -> develop (non-fast-forward)
-#   error: failed to push some refs to '<git repo url>'
-#   hint: Updates were rejected because the tip of your current branch is behind
-#   hint: its remote counterpart. Integrate the remote changes (e.g.
-#   hint: 'git pull ...') before pushing again.
-#   hint: See the 'Note about fast-forwards' in 'git push --help' for details.
-
-# shellcheck disable=SC2154
-echo -n "Push changes merged to ${branch_develop} to ${remote_default_name}: "
-if output="$(git "${git_args[@]}" push "${remote_default_name}" \
-                                       "${branch_develop}" 2>&1)"
+echo -n 'Stage changes to conf file: '
+if output="$(git "${git_args[@]}" add "${conf_file}" 2>&1)"
 then
     echo 'OK'
 else
@@ -201,10 +234,13 @@ else
     exit 1
 fi
 
+# shellcheck disable=SC2059,SC2154
+commit_msg="$(printf "${commit_msg_version_tmpl}" "${release_name}")"
+
+echo -n 'Commit changes to conf file: '
 # shellcheck disable=SC2154
-echo -n "Push changes merged to ${branch_master} to ${remote_default_name}: "
-if output="$(git "${git_args[@]}" push "${remote_default_name}" \
-                                       "${branch_master}" 2>&1)"
+if output="$(git "${git_args[@]}" commit \
+               -m "${commit_msg}" "${conf_file}" 2>&1)"
 then
     echo 'OK'
 else
@@ -215,5 +251,5 @@ fi
 
 
 echo
-echo 'pushing finished release complete'
+echo 'project version update complete'
 echo
diff --git a/code/bin/dd-rt-verify-user-configuration b/code/bin/dd-rt-verify-user-configuration
--- a/code/bin/dd-rt-verify-user-configuration
+++ b/code/bin/dd-rt-verify-user-configuration
@@ -1,19 +1,19 @@
 #!/usr/bin/env bash
 
-# dd-push-release-branch
+# dd-rt-verify-user-configuration
 #
-# push a release branch to remote git repo
+# verify git configuration for current user
 #
 # author  : stefan schablowski
 # contact : stefan.schablowski@desmodyne.com
-# created : 2016-06-06
+# created : 2016-06-16
 
 
-# NOTE: see also ./dd-release
+# NOTE: see also ./dd-rt-release
 
 
 echo
-echo 'push release branch'
+echo 'verify git user configuration'
 echo
 
 
@@ -77,7 +77,6 @@ path_to_rt_lib="${path_to_proj_root}/${path_to_rt_lib}"
 # shellcheck disable=SC1090
 if output="$(source "${path_to_rt_lib}" 2>&1)"
 then
-    # shellcheck disable=SC1090
     source "${path_to_rt_lib}"
 else
     echo "${output}"
@@ -101,13 +100,6 @@ repo_root="$(realpath "${repo_root}")"
 # shellcheck disable=SC2154
 conf_file="${repo_root}/${path_to_target_conf}"
 
-# absolute path to release notes folder
-# shellcheck disable=SC2154
-path_to_release_notes="${repo_root}/${path_to_release_notes}"
-
-# arguments passed to git (not to a sub-command) with every call
-git_args=('-C' "${repo_root}")
-
 
 # -----------------------------------------------------------------------------
 # load script configuration
@@ -129,7 +121,7 @@ fi
 echo -n 'Extract script configuration attributes: '
 # TODO: remove once more attributes
 # shellcheck disable=SC2043
-for attr in version
+for attr in users
 do
     output="$(jq -r ".${attr}" <<< "${config}")"
     if [ -n "${output}" ] && [ "${output}" != 'null' ]
@@ -145,59 +137,61 @@ echo 'OK'
 
 
 # -----------------------------------------------------------------------------
-# configure script parameters, cont. 3
-
-# shellcheck disable=SC2154
-major="$(jq -r '.major' <<< "${version}")"
-minor="$(jq -r '.minor' <<< "${version}")"
-patch="$(jq -r '.patch' <<< "${version}")"
-
-release_name="${major}.${minor}.${patch}"
-
-
-# -----------------------------------------------------------------------------
-# push the release branch
-
-
-# TODO: create script to verify these prerequisites and run earlier than here
-
-# NOTE: this script expects to be called in the following context:
-# dd-release has started a release, updated the project version and created
-# release notes; the target repo is on the release branch and there are no
-# tags yet; only the release branch needs to be pushed to origin
-
-# TODO: deal with improperly set up remotes not using 'origin':
-# git flow heavily relies on that convention:
-#   fatal: No configured push destination.
-#   Either specify the URL from the command-line or configure a remote repository using
-#       git remote add <name> <url>
-#   and then push using the remote name
-#       git push <name>
-
+# verify user configuration
 
 echo
+echo -n 'Verify user git configuration: '
 
-# NOTE: 'git push' alone fails with e.g.
-# fatal: The current branch release/2016.22 has no upstream branch.
-# To push the current branch and set the remote as upstream, use
-#     git push --set-upstream origin release/2016.22
+git_username="$( git -C "${repo_root}" config user.name)"
+git_useremail="$(git -C "${repo_root}" config user.email)"
 
-# shellcheck disable=SC2154
-branch_name="${branch_release_prefix}/${release_name}"
-
-# shellcheck disable=SC2154
-echo -n "Push release branch ${branch_name} to ${remote_default_name}: "
-if output="$(git "${git_args[@]}" push "${remote_default_name}" \
-               --set-upstream "${branch_name}" 2>&1)"
+if [ -n "${git_username}" ] && [ -n "${git_useremail}" ]
 then
     echo 'OK'
 else
-    echo 'ERROR'
-    echo "${output}"
-    exit 1
+    echo 'incomplete'
+
+    current_username="$(id -u -n)"
+
+    # set details for known users automatically
+    # shellcheck disable=SC2154
+    mapfile -t known_users <<< "$(jq -r 'keys[]' <<< "${users}")"
+
+    if ! grep -q "${current_username}" <<< "${known_users[*]}"
+    then
+        # shellcheck disable=SC2154
+        echo "${err_msg_git_conf}"
+        echo
+        exit 1
+    else
+        username="$(jq -r ".[\"${current_username}\"].name"  <<< "${users}")"
+        email="$(   jq -r ".[\"${current_username}\"].email" <<< "${users}")"
+
+        echo "configure settings for known user ${current_username}:"
+
+        echo -n "  git config user.name '${username}': "
+        if output="$(git -C "${repo_root}" config user.name "'${username}'")"
+        then
+            echo 'OK'
+        else
+            echo 'ERROR'
+            echo "    ${output}"
+            exit 1
+        fi
+
+        echo -n "  git config user.email '${email}': "
+        if output="$(git -C "${repo_root}" config user.email "'${email}'")"
+        then
+            echo 'OK'
+        else
+            echo 'ERROR'
+            echo "    ${output}"
+            exit 1
+        fi
+    fi
 fi
 
 
 echo
-echo 'release branch push complete'
+echo 'git user configuration verification complete'
 echo
