[#8]: test if target project config exists, exit with message if not

diff --git a/data/mirror/usr/bin/dd-create-brew-package b/data/mirror/usr/bin/dd-create-brew-package
--- a/data/mirror/usr/bin/dd-create-brew-package
+++ b/data/mirror/usr/bin/dd-create-brew-package
@@ -71,6 +71,12 @@ repo_root="$(realpath "$1")"
 # absolute path to target project configuration
 project_conf="${repo_root}/project.conf"
 
+if [ ! -e "${project_conf}" ]
+then
+    echo "Failed to find project configuration ${project_conf}"
+    exit 1
+fi
+
 # name of target project
 project_name="$(jq -r '.Project' "${project_conf}")"
 
diff --git a/data/mirror/usr/bin/dd-upload-artifacts b/data/mirror/usr/bin/dd-upload-artifacts
--- a/data/mirror/usr/bin/dd-upload-artifacts
+++ b/data/mirror/usr/bin/dd-upload-artifacts
@@ -150,6 +150,12 @@ repo_root="$(realpath "$1")"
 # absolute path to target project configuration
 path_to_proj_conf="${repo_root}/project.conf"
 
+if [ ! -e "${path_to_proj_conf}" ]
+then
+    echo "Failed to find project configuration ${path_to_proj_conf}"
+    exit 1
+fi
+
 # determine git branch of target project to determine distribution channel
 git_branch=$(git -C "${repo_root}" rev-parse --symbolic-full-name --abbrev-ref HEAD)
 
