[#8]: replace camel case by dashes; handle checksum creation errors

diff --git a/data/mirror/usr/bin/dd-create-brew-package-formula b/data/mirror/usr/bin/dd-create-brew-package-formula
--- a/data/mirror/usr/bin/dd-create-brew-package-formula
+++ b/data/mirror/usr/bin/dd-create-brew-package-formula
@@ -83,8 +83,15 @@ project_name="$(jq -r '.Project' "${project_conf}")"
 # package output folder, relative to target project root
 package_folder="$(jq -r '.Artifacts.packages' "${project_conf}")"
 
-# package name is project name in lower case
-package_name="$(echo "${project_name}" | tr '[:upper:]' '[:lower:]')"
+# package name is project name in lower case and camel case
+# amended by dashes, e.g. ReleaseTools --> release-tools:
+# https://github.com/Homebrew/brew/blob/master/ ...
+#  ... docs/Formula-Cookbook.md#a-quick-word-on-naming
+# https://stackoverflow.com/a/10218742
+# https://stackoverflow.com/a/10757348
+package_name="$( echo "${project_name::1}" | tr '[:upper:]' '[:lower:]')"
+package_name+="$(echo "${project_name:1}"  | sed -e 's|\([A-Z]\)|-\1|g' \
+                                           | tr '[:upper:]' '[:lower:]')"
 
 # major minor patch project / package version
 major_version="$(jq -r '.Version.major' "${project_conf}")"
@@ -186,8 +193,27 @@ then
 fi
 mkdir -p "${formula_folder}"
 
+package_path="${package_folder}/${archive_name}"
+
+if [ ! -e "${package_path}" ]
+then
+    # from 'man realpath':
+    #   -m, --canonicalize-missing
+    #          no path components need exist or be a directory
+    echo "Failed to find brew package $(realpath -m "${package_path}")"
+    exit 1
+fi
+
 # calculate SHA256 checksum, required for brew formula
-sha256="$(shasum -a 256 "${package_folder}/${archive_name}" | cut -d ' ' -f 1)"
+if ! output="$(shasum -a 256 "${package_path}")"
+then
+    echo 'Failed to calculate SHA256 checksum for brew package:'
+    echo "${output}"
+    popd > /dev/null
+    exit 1
+fi
+
+sha256="$(echo "${output}" | cut -d ' ' -f 1)"
 
 # shellcheck disable=SC2059
 tmpl_data="$(printf "${tmpl_data_tmpl}" "${sha256}" "${url}" "${version}")"
@@ -197,10 +223,7 @@ formula_tmpl="${formula_tmpl_folder}/${formula_tmpl_name}"
 
 if [ ! -e "${formula_tmpl}" ]
 then
-    # from 'man realpath':
-    #   -m, --canonicalize-missing
-    #          no path components need exist or be a directory
-    echo "Failed to find brew formula template $(realpath -m ${formula_tmpl})"
+    echo "Failed to find brew formula template $(realpath -m "${formula_tmpl}")"
     exit 1
 fi
 
