[#10]: run git flow init if required

diff --git a/dd-release/data/mirror/usr/bin/dd-start-release b/dd-release/data/mirror/usr/bin/dd-start-release
--- a/dd-release/data/mirror/usr/bin/dd-start-release
+++ b/dd-release/data/mirror/usr/bin/dd-start-release
@@ -32,7 +32,6 @@ fi
 # TODO: prevent processing repo this file is in during development ?
 # TODO: verify required executables are available before using them ?
 # TODO: script return value when run as Jenkins job ?!?
-# TODO: run git flow init if required ?
 # TODO: verify release branch to create does not exist on remote yet ?
 # TODO: add leading zero to calender week in release name
 # TODO: do something with the output when script succeeds, e.g.
@@ -61,6 +60,9 @@ repo_root="$(realpath "$1")"
 # publish the efforts of the past week, the calender week is that of last week
 release_name="$(date +"%Y").$(( $(date +"%V") - 1))"
 
+# one error message that might occur and should be dealt with
+err_msg='fatal: Not a gitflow-enabled repo yet. Please run "git flow init" first.'
+
 
 # NOTE: pushd / popd require bash
 pushd "${repo_root}" > /dev/null
@@ -70,15 +72,26 @@ pushd "${repo_root}" > /dev/null
 # start the release
 
 echo "Start release ${release_name} in ${repo_root}:"
-git flow release start "${release_name}"
+# this assumes git prints to either stdout or stderr,
+# but not both - and sets a corresponding return value
+output=$(git flow release start "${release_name}" 2>&1)
 
 res="$?"
 
 if [ "${res}" -ne 0 ]
 then
-    # git flow release start prints its own error messages
-    popd > /dev/null
-    exit "${res}"
+    if [ "${output}" = "${err_msg}" ]
+    then
+        echo 'Not a gitflow-enabled repo yet; run "git flow init" with defaults:'
+        # -d : use default branch names
+        git flow init -d
+        res="$?"; if [ "${res}" -ne 0 ]; then popd > /dev/null; exit "${res}"; fi
+    else
+        # git flow release start prints its own error messages
+        echo "${output}"
+        popd > /dev/null
+        exit "${res}"
+    fi
 fi
 
 
